# Generated by Django 5.0.4 on 2024-04-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('parking_lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, unique=True)),
                ('address', models.CharField(max_length=150)),
                ('price_first_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_additional_hour', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
