# Generated by Django 5.0.4 on 2024-04-10 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
    ]
