FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./

RUN dotnet tool install --global dotnet-ef --version 8.0.4
ENV PATH="$PATH:/root/.dotnet/tools"

RUN dotnet build -c Release

ENTRYPOINT ["dotnet", "ef", "database", "update"]
